// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Arrow: typeof import('./src/components/Arrow.vue')['default']
    Avatar: typeof import('./src/components/tabItems/Avatar.vue')['default']
    Award: typeof import('./src/components/tabItems/Award.vue')['default']
    Education: typeof import('./src/components/tabItems/Education.vue')['default']
    LeftContent: typeof import('./src/components/LeftContent.vue')['default']
    LeftHeader: typeof import('./src/components/LeftHeader.vue')['default']
    LeftTabs: typeof import('./src/components/LeftTabs.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NFormItemGi: typeof import('naive-ui')['NFormItemGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NRate: typeof import('naive-ui')['NRate']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    PdfAvatar: typeof import('./src/components/rightItems/PdfAvatar.vue')['default']
    PdfAward: typeof import('./src/components/rightItems/PdfAward.vue')['default']
    PdfEducation: typeof import('./src/components/rightItems/PdfEducation.vue')['default']
    PdfProfile: typeof import('./src/components/rightItems/PdfProfile.vue')['default']
    PdfProject: typeof import('./src/components/rightItems/PdfProject.vue')['default']
    PdfSkill: typeof import('./src/components/rightItems/PdfSkill.vue')['default']
    PdfWork: typeof import('./src/components/rightItems/PdfWork.vue')['default']
    Profile: typeof import('./src/components/tabItems/Profile.vue')['default']
    Project: typeof import('./src/components/tabItems/Project.vue')['default']
    RightContent: typeof import('./src/components/RightContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skill: typeof import('./src/components/tabItems/Skill.vue')['default']
    Tag: typeof import('./src/components/Tag.vue')['default']
    Work: typeof import('./src/components/tabItems/Work.vue')['default']
  }
}
